basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for finance management
  title: Finance App API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
